version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            wget -O ./delphi4py.whl $delphi4py_whl
            pipenv install delphi4py.whl
            pipenv lock

      - save_cache:
          path: ./
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python2.7/site-packages"
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            cd pypka/tests/
            pipenv run python test.py