version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile.lock" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            wget -O ./delphi4py-1.0.1-py2-none-any.whl $delphi4py_whl
            pipenv install ./delphi4py-1.0.1-py2-none-any.whl pytest
            pipenv lock

      - save_cache:
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python2.7/site-packages"
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: run tests
          command: |
            set -e
            cd pypka/tests/
            pipenv run pytest test.py