version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            wget -O ./delphi4py.whl $delphi4py_whl
            pipenv install delphi4py.whl
            pipenv lock

      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            pipenv shell
            cd pypka/tests/
            exit
